name: getAllRepliesToKnownPosts2
concurrency: get_context2

on:
  workflow_dispatch:
  schedule:
     - cron: '7,17,27,37,47,57 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    environment: mastodon2
    permissions:
      contents: write
    steps:
      - name: Checkout original repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.10'
         cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          name: artifacts
          workflow: get_context2.yml
          if_no_artifact_found: warn
          path: artifacts
      - name: Get Directory structure
        run: ls -lR
      - run: python find_posts.py --lock-hours=0 --access-token="${{ secrets.ACCESS_TOKEN2 }}" -c="./config2.json"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            artifacts
#      - name: Checkout user's forked repository for keeping workflow alive
#        uses: actions/checkout@v4
#      - name: Keep workflow alive
#        uses: gautamkrishnar/keepalive-workflow@v1
